---
title: "Federated_Learning"
author: "Jeffrey Waters & Nathan Szeto"
date: "2024-02-23"
output: pdf_document
---

# Load Federated Learning Data
```{r}
load("jeff.RData")
load("nathan.RData")

# Compiles list of Summary Statistics into a single list
fed_data <- list(g1=l1, g2=l2)
```

```{r}
# FEDERATED LERANING FUNCTIONS FOR MEAN AND LINEAR REGRESSION

Federated_mean <- function(groups){
  # Only need n_i and y_bar_i for this
  
  # sum up the n_i to get n
  n <- sum(sapply(groups, function(x) x$n))
  y_bar <- 0
  
  for (group in groups){
    y_bar_i <- group["y_bar"][[1]]
    n_i <- group["n"][[1]]
    
    y_bar <- y_bar + n_i/n * y_bar_i
  }
  
  return(y_bar)
}



Federated_LR <- function(groups){
  # groups 
  # Initialize SSX and SSXY and SSY
  
  
  SSX <- groups[[1]][[1]]  * 0    # pxn * nxp = pxp matrix
  SSXY <- groups[[1]][[2]] * 0   # pxn * nx1 = px1
  SSY <- groups[[1]][[3]]  * 0    # 1xn * nx1 = 1x1
  
  n <- 0
  p <- nrow(SSX) # SSX is a pxp matrix
  
  # Estimate Betas
  for (group in groups){
    SSX_i <- group["SSX"][[1]]
    SSXY_i <- group["SSXY"][[1]]
    SSY_i <- group["SSY"][[1]]
    n_i <- group["n"][[1]]
    
    SSX <- SSX + SSX_i
    SSXY <- SSXY + SSXY_i
    SSY <- SSY + SSY_i
    n <- n + n_i
  }
  
  # pxp * px1 = px1
  #Regularization parameter to make SSX solvable
  #lambda <- 0.01
  #SSX <- SSX + diag(lambda, nrow(SSX))

  beta_hat <- solve(SSX) %*% SSXY
  colnames(beta_hat) <- c("Estimate")
  
  
  # Get the MSE(mean squared estimator)
  MSE_num <- SSY - 2 * t(beta_hat) %*% SSXY + t(beta_hat) %*% SSX %*% beta_hat
  MSE <- c(MSE_num / (n - p))
  
  
  # Calculate Standard Error of beta hat:
  se <- sqrt(MSE * diag(solve(SSX)))
  se <- matrix(se, nrow(beta_hat), ncol=1)
  colnames(se) <- c("Std. Error")
  
  
  
  # Calculate t-values
  t_values <- beta_hat / se
  colnames(t_values) <- c("t_value")
  
  # Calculate p-values
  p_values <- apply(t_values, MARGIN=2, FUN=function(x) 2 * (1 - pt(abs(x), n-p)))
  colnames(p_values) <- c("Pr(>|t|)")
  
  summary_mat <- cbind(beta_hat, se, t_values, p_values)
  summary_mat <- as.data.frame(summary_mat)
  
  # Print 95% CI intervals:
  CI_95 <- paste("(", 
                             round(summary_mat$Estimate - 1.96 * summary_mat[,"Std. Error"], 3), 
                             ", ", 
                             round(summary_mat$Estimate + 1.96 * summary_mat[,"Std. Error"], 3),
                             ")"
  )
  
  summary_mat <- summary_mat %>% round(3)
  summary_mat$CI_95 <- CI_95
  
  print(summary_mat)
  #RSS = residual sum of squares
  RSS <- MSE_num
  
  # Calculate coefficient of determination
  
  y_bar <- Federated_mean(groups)
  #Total Sum of Squares
  TSS <- SSY - n * y_bar^2
  
  R2 <- 1 - ( RSS/ (n - p) ) / (TSS / (n - 1) )
  
  # Print R2
  cat(sprintf("R2: %f \n", round(R2, 3)))
  
}

```

```{r}
Federated_LR(fed_data)
```